---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribble: http://dribbble.com/...
#  license: SIL
#  license_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%. 
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
#
################################################################################
#


meta:
  author: isux
  homepage: http://isux.tencent.com/
  twitter: https://twitter.com/isux/
  license: CC BY-SA 3.0
  license_url: http://creativecommons.org/licenses/by-sa/3.0/

  css_prefix_text: "icon-"
  columns: 4

#transform:
#  baseline: 0.5
#  rescale: 1.053
#  # offset: -0.05


font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: sola-aoi

  fullname: sola-aoi
  familyname: sola-aoi

  copyright: (c) isux tencent 2013

  ascent: 850
  descent: 150
  weight: "Regular"


glyphs:

  -
    css: at
    code: 0xf798
    uid: d97f2667f3da0845da7baaeda485e2da 
    search: [at]
  -
    css: activity
    code: 0xf800
    uid: d522bf9b0fbe1e8c501db1ff871b359f 
    search: [activity]
  -
    css: app-add
    code: 0xf861
    uid: 3aa86a7bb0229b2a681f39ae7a2441a6 
    search: [app]
  -
    css: app-center
    code: 0xf862
    uid: f220a344361b32db28c66048168faf9c 
    search: [app, center]
  -
    css: app-center2
    code: 0xf826
    uid: ce8a6dc1b032ced1d414c1b61098dfe3 
    search: [app, center]
  -
    css: arrow-top
    code: 0xf863
    uid: ec94ff56b8332bd3edc3a4e90e7749e7 
    search: [arrow, top]
  -
    css: cert
    code: 0xf865
    uid: f6474f6853e2276e536c8993268d5fca 
    search: [cert]
  -
    css: cloudy
    code: 0xf866
    uid: 7ce2e72d9618a8fbf8a48929b7a21129 
    search: [cloudy, weather]
  -
    css: whirlwind
    code: 0xf799
    uid: 80690177904a56387cf13d0b4391012e
    search: [whirlwind, weather]
  -
    css: sandstorm
    code: 0xf796
    uid: 99cb2e0b1f773a7a0db53cf6fca4e988 
    search: [sandstorm, weather]
  -
    css: sink-float
    code: 0xf795
    uid: 8d436ba168d8827137b31b619ccc3b82 
    search: [sink-float, weather]
  -
    css: snow-shower
    code: 0xf794
    uid: b46fc0e51e4d2c0727544515af38b5cd 
    search: [snow, shower, weather]
  -
    css: fog
    code: 0xf793
    uid: 2ae59c9d0f454344656b6f5c9823527f 
    search: [fog, weather]
  -
    css: tornado
    code: 0xf792
    uid: 8db23f7c6e49b7b837e0497edb616379 
    search: [tornado, weather]
  -
    css: sleet
    code: 0xf791
    uid: 6f903f13e9906da87b5721dd09cdd57f 
    search: [sleet, weather]
  -
    css: mist
    code: 0xf790
    uid: b92b07dd4153bd0ae92a30af37591758 
    search: [mist, weather]
  -
    css: big-snow
    code: 0xf789
    uid: 0941a65ff9c4878d9510092142738eb3 
    search: [big-snow, weather]
  -
    css: middle-snow
    code: 0xf788
    uid: f8ad5d78931dffc432d9e3818fd535d4 
    search: [middle-snow, weather]
  -
    css: little-snow
    code: 0xf787
    uid: 6e61158cace490f082aeaca8774602b2 
    search: [little-snow, weather]
  -
    css: jansha
    code: 0xf786
    uid: 313c3a7f03047701ebffe740c861c8ca 
    search: [jansha, weather]
  -
    css: heavy-rainstorm
    code: 0xf785
    uid: 220d1186e4531efd3cf2d9c6f5d0550b
    search: [heavy-rainstorm, rain, weather]
  -
    css: rainstorm
    code: 0xf784
    uid: 591eb82556912be5fc5dec042966b829 
    search: [rainstorm, weather]
  -
    css: drizzle
    code: 0xf783
    uid: 64dc76cdb216e596bd9f5fe18a3a9709 
    search: [drizzle, weather]
  -
    css: thunderstorms
    code: 0xf782
    uid: cfa679fb0891b245759b2f2e04e6963b 
    search: [thunderstorms, weather]
  -
    css: shower
    code: 0xf780
    uid: 75017cf8f731a49394e3895361314f5d 
    search: [shower, weather]
  -
    css: cloudy2
    code: 0xf781
    uid: 2089d155f2bd21c9a7d366f3a851b1b2 
    search: [cloudy, weather]
  -
    css: hail
    code: 0xf779
    uid: 690136fdbe5deeb07948186bbec6153f
    search: [hail, weather]
  -
    css: sunny
    code: 0xf778
    uid: 2b506809771e621dbe68674e8c1f9095 
    search: [sunny, weather]
  -
    css: middle-rain
    code: 0xf776
    uid: 2802caff4c3bea01e28c59ec61bab03f 
    search: [middle-rain, weather]
  -
    css: heavy-rain
    code: 0xf774
    uid: d22a9fe9f197cb9ef53139cb57c4fd09 
    search: [heavy-rain, weather]
  -
    css: rain-snow
    code: 0xf775
    uid: 7fd9843ce2180227309babd114d7c168 
    search: [rain, snow, weather]
  -
    css: dress
    code: 0xf867
    uid: b7456e47f7f5b65b43002ca73aa24978 
    search: [dress]
  -
    css: gift
    code: 0xf868
    uid: d3f8eb91dea871ad107fc0360b9ff171 
    search: [gift]
  -
    css: homepage
    code: 0xf869
    uid: b7e2aee962ff7c39b5c86eca087af247 
    search: [homepage]
  -
    css: zan
    code: 0xf871
    uid: 0e74d2ca29545fa136f86b624f14ea0e 
    search: [zan, like]
  -
    css: zan2
    code: 0xf870
    uid: 9d42e2e7585e0095e9e187e0bec2e2b2 
    search: [like, zan]
  -
    css: list-more
    code: 0xf872
    uid: e0b38208d9d176a230ed13b9cd67ba03 
    search: [list, more]
  -
    css: love
    code: 0xf873
    uid: ca067dd82971bf903278a81a3d227f1d 
    search: [love]
  -
    css: mail
    code: 0xf874
    uid: 12b380d0d2ab84c3247554a38e16cf9e 
    search: [mail]
  -
    css: myhome
    code: 0xf875
    uid: a136da43c30d3c8e34b5b328dec920e1 
    search: [myhome, home]
  -
    css: pengyou
    code: 0xf876
    uid: cb6c4d8bde4e9338951335c202118b68 
    search: [pengyou,logo,tencent]
  -
    css: search
    code: 0xf877
    uid: 55c6cc587abf8016c88193a1b20cdb27 
    search: [search]
  -
    css: arrow-down
    code: 0xf890
    uid: ab90f08ccb5cc45b829a338a45a413a9 
    search: [arrow,down,tencent]
  -
    css: arrow-up
    code: 0xf891
    uid: f6f69e7e826958508a5fafd3dec9b089 
    search: [arrow,tencent,up]
  -
    css: play
    code: 0xf894
    uid: 2867980df2e920df50b1790ea661e8df 
    search: [play,media,qzone]
  -
    css: pause
    code: 0xf895
    uid: f8d0a1212fc44839760c86137386d4d2 
    search: [pause,media,qzone]
  -
    css: add
    code: 0xf897
    uid: d48ba6a6715bdfb3f9a7623413f41983 
    search: [add,qzone]
  -
    css: edit
    code: 0xf89a
    uid: aa2a55de5f51843ef29365e21962057e 
    search: [edit,qzone]
  -
    css: zoom-in
    code: 0xf89b
    uid: e1ab694ce3a10660153a8f02d2219d1a 
    search: [zoom-in,qzone]
  -
    css: zoom-out
    code: 0xf89c
    uid: e51be0ebcd61cb511c5a1067cc61093e
    search: [zoom-out,qzone]
  -
    css: image
    code: 0xf88c
    uid: 0178750590ab32929c3dca2076b8bb82 
    search: [image,qzone]
  -
    css: mark-man
    code: 0xf90a
    uid: 693d2eccc36cf0840cbf41c9594fb835
    search: [mark-man,qzone]
  -
    css: hometown
    code: 0xf90b
    uid: 548b46bef3df65d1f87303353eba6b60 
    search: [hometown,qzone]
  -
    css: remove
    code: 0xf90c
    uid: 012e077dfe0878888e9ea00e73d72dac 
    search: [remove,qzone]
  -
    css: master
    code: 0xf90d
    uid: 93fc4b39eabb99970762632a778ce4f2 
    search: [master,qzone]
  -
    css: timing
    code: 0xf90e
    uid: ebed6d0826ca8a94da425f137c0f9dcd 
    search: [timing,qzone]
